xPackage, fixes bug using the file hash
dsccommunity/xPSDesiredStateConfiguration pull request #703
Opened 2020-11-25 12:45 UTC by raandree

#### Pull Request (PR) description
When trying to install or uninstall a software package using xPackage and providing a file hash, this error is thrown:

```
PowerShell DSC resource DSC_xPackageResource  failed to execute Set-TargetResource functionality with error message: The parameter "Hash" is 
declared in parameter-set "__AllParameterSets" multiple times. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
```

#### This Pull Request (PR) fixes the following issues
- Fixes #702

#### Task list
- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

2020-11-25 22:24 UTC, raandree commented
@PlagueHO, there is not much to review... :)

2020-11-26 04:35 UTC, PlagueHO requested changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/703)* status: all files reviewed, 1 unresolved discussion (waiting on @raandree)

___
*[CHANGELOG.md, line 9 at r2](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/703#-MN1pCPc7p6dQGFG6ZvI:-MN1pCPc7p6dQGFG6ZvJ:b-h1am2l) ([raw file](https://github.com/dsccommunity/xpsdesiredstateconfiguration/blob/1db92ecd64e6256588f6cd9aea3b182c359136a4/CHANGELOG.md#L9)):*
> ```
> (#702).
> ```
Can you use style:
```
- Fixes [Issue #687](https://github.com/dsccommunity/xPSDesiredStateConfiguration/issues/687).
```

This is so the MD has a link.


<!-- Sent from Reviewable.io -->

2020-12-01 05:34 UTC, shs8313 approved these changes

2020-12-01 05:37 UTC, shs8313 approved these changes

2020-12-01 06:45 UTC, PlagueHO commented
Hi @raandree - it looks like the tests are failing on this one. Can you validate and I'll review?

2020-12-01 06:46 UTC, PlagueHO commented
Hi @raandree - just need one minor tweak and I'll merge.

2020-12-03 18:40 UTC, raandree reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/703)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @PlagueHO)

___
*[CHANGELOG.md, line 9 at r2](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/703#-MN1pCPc7p6dQGFG6ZvI:-MNdtuAl-hdpVNInG5kJ:b-896fix) ([raw file](https://github.com/dsccommunity/xpsdesiredstateconfiguration/blob/1db92ecd64e6256588f6cd9aea3b182c359136a4/CHANGELOG.md#L9)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

> ```
> (#702).
> ```
Can you use style:
```
- Fixes [Issue #687](https://github.com/dsccommunity/xPSDesiredStateConfiguration/issues/687).
```

This is so the MD has a link.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-06 06:50 UTC, PlagueHO approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/703)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-12-06 06:50 UTC, merged

2020-12-06 06:51 UTC, PlagueHO commented
:lgtm: